# Generated by Django 5.0.3 on 2024-09-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_conversationmodel_messagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="conversation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.conversationmodel",
            ),
        ),
    ]
